import Head from "next/head";
import React, { useState } from "react";

import { Movies, data } from "../movies";
import { Header } from "../components/Header";
import { MyGlobalContext } from "./context";

export default function Home(): JSX.Element {
  const [movies, setMovies] = useState<Movies[]>(data);
  return (
    <MyGlobalContext.Provider value={{ movies, setMovies }}>
      <div>
        <Head>
          <title>c4t movie app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container mx-auto py-36 px-2 font-mono">
          <Header />
        </main>
      </div>
    </MyGlobalContext.Provider>
  );
}
